
<?php
$model = $this->loadByField();

?> 
<table border='3' style='width:100%;' class="data-table cart-table" >
    <tr class="first last">
        <th>Profile Id</th>
        <th>User Id </th>
        <th>User Name</th>
        <th>First Name</th>
        <th>Last Name</th>

    </tr>


    <?php foreach ($model as $item) { ?>

        <tr >
            <td > <?php echo $item['profile_id']; ?></td>
            <td > <?php echo $item['user_id']; ?></td>
            <td> <?php echo $item['user_name']; ?></td>
            <td> <?php echo $item['first_name']; ?></td>
            <td> <?php echo $item['last_name']; ?></td>


        </tr>

    <?php } ?>  

</table>
<a  href="index/insert"> Add New Row</a>









