
<?php
$model = $this->loadByField();
?> 

<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('User Information') ?></h1>
</div>  

<table class="data-table orders" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('Profile Id') ?></th>
            <th class="date"><?php echo $this->__('User Id') ?></th>
            <th class="ship"><?php echo $this->__('User Name') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('First Name') ?></span></th>
            <th class="total"><span class="nobr"><?php echo $this->__('Last Name') ?></span></th>
            <th class="status"><span class="nobr"><?php echo $this->__('Update') ?></span></th>
            <th class="view"><span class="nobr"><?php echo $this->__('Dalete') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php  $_odd = ''; ?>
        <?php foreach ($model as $_order) : ?>
            <tr >
                <td class="number"><?php echo $_order['profile_id'] ?></td>
                <td class="date"><span class="nobr"><?php echo $_order['user_id'] ?></span></td>
                <td class="ship"><?php echo $_order['user_name'] ?></td>
                <td class="total"><?php echo $_order['first_name'] ?></td>
                <td class="status"><em><?php echo $_order['last_name'] ?></em></td>

                <td> <a href="index/update?edit_id=<?php echo($_order['user_id']); ?>"  >Update</a></td>
                <td> <a href="?id=<?php echo($_order['user_id']); ?>" class="link-reorder">Delete</a></td>

            </tr>
       <?php endforeach; ?>
    </tbody>
</table>
    
<div class="buttons-set">
    <p class="back-link"><a href="index/insert"><small></small>Add New Row</a></p>
</div>

<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>

  

